#!/usr/bin/expect -f
set timeout 120
set server_ip "118.178.242.26"
set server_user "root"
set server_password "bcefghj@Github666"

if {[llength $argv] < 2} {
    puts "Usage: ./scp_upload.exp local_file remote_path"
    exit 1
}

set local_file [lindex $argv 0]
set remote_path [lindex $argv 1]

spawn scp -o StrictHostKeyChecking=no $local_file $server_user@$server_ip:$remote_path

expect {
    "password:" {
        send "$server_password\r"
        expect eof
    }
    "Password:" {
        send "$server_password\r"
        expect eof
    }
    eof {}
    timeout {
        puts "TIMEOUT"
        exit 1
    }
}

wait
