#!/usr/bin/expect -f
set timeout 300
set server_ip "118.178.242.26"
set server_user "root"
set server_password "bcefghj@Github666"

if {[llength $argv] == 0} {
    puts "Usage: ./ssh_deploy_quick.exp \"command\""
    exit 1
}

set command [lindex $argv 0]

spawn ssh -o StrictHostKeyChecking=no $server_user@$server_ip $command

expect {
    "password:" {
        send "$server_password\r"
        expect eof
    }
    "Password:" {
        send "$server_password\r"
        expect eof
    }
    eof {}
    timeout {
        puts "TIMEOUT"
        exit 1
    }
}

wait
